### ISSUE TITLE
作者你好，我发现一个问题（可能），我是小白）

### ISSUE THREAD

**Issue by wangweng** [Akakiiiiii/cli3music#2]
我直接 npm run serve 它可以登录，但是我 npm run build 打包后放到服务器上后它就登陆不了了，具体情况为登陆后它就变成空白页面，会卡死，并且刷新也动不了，只能换一个浏览器或换一个设备才能上网站。

**Comment by Akakiiiiii** [comment]
打包并且上传至服务器后别的功能与请求正常吗，只有登录一个功能不行吗

**Comment by wangweng** [comment]
是的，其他功能挺正常的。

**Comment by Akakiiiiii** [comment]
检查一下你的浏览器是不是设置了默认不发送cookie的设置呢，因为登录后后端会给页面设置一段cookie

**Comment by Akakiiiiii** [comment]
我之前写别的项目的时候也遇到过这样的情况，我的问题是因为前端的端口被占用了，然后我把前端的端口换了一个就好了，或许你把你的服务器配置前端的端口换一下就可以解决问题

**Comment by wangweng** [comment]
好的，我明天去研究一下，非常感谢，晚安。

**Comment by Akakiiiiii** [comment]
加油，我也是小小白，晚安
